### ISSUE TITLE
Feature Request - Number of pixels

### ISSUE THREAD

**Issue by mklabunde1** [Pixelcontroller/f-test_issues#3]
Could you add a way to change the pixel count 10's 100's.  You use the up and down but are changing the 10's place or the 100's place so you can zero out the 1000 and then move to the 100's place and change that so you don't have to go all the way around to lets say 500 pixels. 

Thanks,
Mark

**Comment by DoctorWiz** [comment]
Or could you add an 'acceleration' algorithm so that the longer you hold the button, the faster in increments or decrements.  Or much better yet, save the last number of pixels used into non-volatile memory.

**Comment by Indigogyre** [comment]
It takes literally 2 minutes 45 seconds to go from the default 1400 pixels to get down to 100 pixels. Each and every time you turn it on and want to work with using pixels out. Please do something about this.

**Comment by dpitts** [comment]
HI

We can possibly implement a quicker method. Please note you can save settings which include pixel count.

Thank you,

David Pitts
***@***.***

**Comment by keithsw1111** [comment]
I have implemented the hold and speed up but if you want to save the setting that is already possible ... just go in and set it then go out and select save settings. This saves all settings including that pixel count so they will be the default on next boot.

Essentially if you hold for > 1 second it jumps by 50s ... then you need to do short bursts for fine adjustment. I did consider a smaller fast jump but this seemed to be the best balance. Once you have it dialed in use the save settings so it starts there in future uses.

Build 3 is available for download in this repository.

**Comment by Indigogyre** [comment]
I've updated my F-Test and everything is working properly. Also, I missed the part in the manual that stated it would save settings from other areas.

Thank you for your quick help and resolution.
